// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface IPanels {
    data: IPanel[];
}

export interface IPanel {
    id:       number;
    title:    Title;
    category: Category;
    intro:    Intro;
    details: string[];
    isFav?:   boolean
}

export enum Category {
    Information = "information",
    Iot = "iot",
    Network = "network",
}

export enum Intro {
    ProvideCommunicationOfDataBetweenIOTDevices = "Provide communication of data between IOT devices",
    ProvidesSupportForEventAlerts = "Provides support for event alerts",
    ThisWillProvideNetworkDataSupportAndReporting = "This will provide network data support and reporting",
}

export enum Title {
    DataController = "Data Controller",
    EventAlerts = "Event Alerts",
    Transfer = "Transfer",
}
